source 'https://rubygems.org'

gem 'asciidoctor',         '~> 2.0'
gem 'asciidoctor-pdf',     '~> 2.3'
gem 'asciidoctor-epub3',   '~> 2.1'
gem 'asciidoctor-diagram', '~> 2.3'
gem 'rouge',               '~> 4.0'
gem 'logger'
